package Main;

import Conexion.Conexion;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Product extends javax.swing.JFrame {

    private void limpiarCajas() {

    txtUnitsON.setText(null);
    txtCategoryID.setText(null);
    txtDiscontinued.setText(null);
    txtProductName.setText(null);
    txtQuantity.setText(null);
    txtReorderLeverl.setText(null);  
    txtSupplierd.setText(null);
    txtUniprice.setText(null);
    txtUnitsStock.setText(null);
}
    public Product() {
        initComponents();
        try {
        cargarTabla();
    } catch (SQLException ex) {
        Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscarproductos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSupplierd = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        txtCategoryID = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtUniprice = new javax.swing.JTextField();
        txtUnitsStock = new javax.swing.JTextField();
        txtUnitsON = new javax.swing.JTextField();
        txtReorderLeverl = new javax.swing.JTextField();
        txtDiscontinued = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtProductId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Products");

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "productId ", "productName", "supplierId ", "categoryId ", "quantityPerUnit", "unitPrice", "unitsInStock", "unitsOnOrder", "reorderLevel", "discontinued"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscarproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarproductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscarproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnBuscar)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel2.setText("discontinued");

        jLabel3.setText("productName");

        jLabel4.setText("supplierId ");

        jLabel5.setText("categoryId ");

        jLabel6.setText("quantityPerUnit");

        jLabel7.setText("unitPrice");

        jLabel8.setText("unitsInStock");

        jLabel9.setText("unitsOnOrder");

        jLabel10.setText("reorderLevel");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtProductId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProductId.setText("Ingrese productId a modificar o eliminar");
        txtProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addGap(14, 14, 14)))
                                .addGap(109, 109, 109)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProductName)
                                    .addComponent(txtSupplierd)
                                    .addComponent(txtCategoryID)
                                    .addComponent(txtQuantity)
                                    .addComponent(txtUniprice)
                                    .addComponent(txtUnitsStock)
                                    .addComponent(txtUnitsON)
                                    .addComponent(txtReorderLeverl)
                                    .addComponent(txtDiscontinued, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificar)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnLimpiar)
                                        .addGap(61, 61, 61)
                                        .addComponent(btnEliminar))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(jLabel3)
                                                                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel4)
                                                                    .addComponent(txtSupplierd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(19, 19, 19)
                                                                .addComponent(jLabel5))
                                                            .addComponent(txtCategoryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(21, 21, 21)
                                                        .addComponent(jLabel6))
                                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7))
                                            .addComponent(txtUniprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addComponent(txtUnitsStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(txtUnitsON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(txtReorderLeverl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtDiscontinued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(29, 29, 29)
                .addComponent(btnModificar)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarproductosActionPerformed
    
    }//GEN-LAST:event_txtBuscarproductosActionPerformed
    private boolean esNumeroPositivo(String texto) {
        try {
            double numero = Double.parseDouble(texto);
            return numero >= 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtCategoryID.getText().isEmpty() || txtDiscontinued.getText().isEmpty() || txtProductName.getText().isEmpty() ||
        txtQuantity.getText().isEmpty() || txtReorderLeverl.getText().isEmpty() || txtSupplierd.getText().isEmpty() ||
        txtUniprice.getText().isEmpty() || txtUnitsON.getText().isEmpty() || txtUnitsStock.getText().isEmpty()) {   
        JOptionPane.showMessageDialog(null, "Por favor, completa todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return; 
        }

        if (!esNumeroPositivo(txtCategoryID.getText()) || !esNumeroPositivo(txtDiscontinued.getText()) || !esNumeroPositivo(txtReorderLeverl.getText())
                || !esNumeroPositivo(txtSupplierd.getText())|| !esNumeroPositivo(txtUniprice.getText())|| !esNumeroPositivo(txtUnitsON.getText())
                || !esNumeroPositivo(txtUnitsStock.getText())) 
        {
        JOptionPane.showMessageDialog(null, "Ingrese solo números en los campos (a exepcion de ProductName y quantityPerUnit)", "Error de entrada", JOptionPane.WARNING_MESSAGE);
        return;
        }

        Connection con;
        try {
            
            con =Conexion.getConexion();   
                    
            PreparedStatement ps = con.prepareStatement("INSERT INTO product(productName, supplierId , categoryId, quantityPerUnit, unitPrice, unitsInStock, unitsOnOrder, reorderLevel, discontinued) VALUES(?,?,?,?,?,?,?,?,?) ");
            ps.setString(1, txtProductName.getText());
            ps.setInt(2,Integer.parseInt( txtSupplierd.getText()));
            ps.setInt(3, Integer.parseInt(txtCategoryID.getText()));
            ps.setString(4, txtQuantity.getText());
            ps.setDouble(5, Double.parseDouble(txtUniprice.getText()));
            ps.setString(6, txtUnitsStock.getText());
            ps.setString(7, txtUnitsON.getText());
            ps.setString(8,  txtReorderLeverl.getText());
            ps.setString(9, txtDiscontinued.getText());
            
            int res = ps.executeUpdate();

        if (res > 0) {
            JOptionPane.showMessageDialog(null, "Product Guardado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error al Guardar product");
        }
			
	limpiarCajas();
        
        con.close();
        cargarTabla();
    }       
   catch (SQLException e) {
    if (e.getSQLState().equals("23000") && e.getErrorCode() == 2627) {
        JOptionPane.showMessageDialog(null, "El product ya esta registrada en la base de datos.", "Error de inserción", JOptionPane.ERROR_MESSAGE);
    } else {
        e.printStackTrace(); 
    }
} 
    }//GEN-LAST:event_btnGuardarActionPerformed
    private void cargarTabla() throws SQLException{
        DefaultTableModel modeloTabla = (DefaultTableModel) tblProducts.getModel();
        
        modeloTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        try {
        Connection con =Conexion.getConexion();  
        ps  = con.prepareStatement("select * from product");
        
        rs = ps.executeQuery();
        rsmd=rs.getMetaData();
        columnas=rsmd.getColumnCount();
        
        while(rs.next()){
            Object[] fila= new Object[columnas];
            for(int indice =0; indice<columnas;indice++){
                fila[indice]=rs.getObject(indice+1);
            }
            modeloTabla.addRow(fila);
        }
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    } 
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCajas();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (txtCategoryID.getText().isEmpty() || txtDiscontinued.getText().isEmpty() || txtProductName.getText().isEmpty() ||
        txtQuantity.getText().isEmpty() || txtReorderLeverl.getText().isEmpty() || txtSupplierd.getText().isEmpty() ||
        txtUniprice.getText().isEmpty() || txtUnitsON.getText().isEmpty() || txtUnitsStock.getText().isEmpty()) {   
        JOptionPane.showMessageDialog(null, "Por favor, completa todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return; 
        }
        
        if (!esNumeroPositivo(txtCategoryID.getText()) || !esNumeroPositivo(txtDiscontinued.getText()) || !esNumeroPositivo(txtReorderLeverl.getText())
                || !esNumeroPositivo(txtSupplierd.getText())|| !esNumeroPositivo(txtUniprice.getText())|| !esNumeroPositivo(txtUnitsON.getText())
                || !esNumeroPositivo(txtUnitsStock.getText())) {
        JOptionPane.showMessageDialog(null, "Ingrese solo números en los campos (a exepcion de ProductName y quantityPerUnit)", "Error de entrada", JOptionPane.WARNING_MESSAGE);
        return;
        }
    
    Connection con;

    try {
        con = Conexion.getConexion();
        PreparedStatement ps = con.prepareStatement("UPDATE product SET  productName=?, supplierId=? , categoryId=?, quantityPerUnit=?, unitPrice=?, unitsInStock=?, unitsOnOrder=?, reorderLevel=?, discontinued=? where productId =?");
            ps.setString(1, txtProductName.getText());
            ps.setInt(2,Integer.parseInt( txtSupplierd.getText()));
            ps.setInt(3, Integer.parseInt(txtCategoryID.getText()));
            ps.setString(4, txtQuantity.getText());
            ps.setDouble(5, Double.parseDouble(txtUniprice.getText()));
            ps.setString(6, txtUnitsStock.getText());
            ps.setString(7, txtUnitsON.getText());
            ps.setString(8,  txtReorderLeverl.getText());
            ps.setString(9, txtDiscontinued.getText());
            ps.setInt(10,Integer.parseInt( txtProductId.getText()));
            
        int res = ps.executeUpdate();

        if (res > 0) {
            JOptionPane.showMessageDialog(null, "Produc Modificado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error al Modificar product");
        }
        limpiarCajas();
        con.close();
        cargarTabla();

    } catch (HeadlessException | SQLException e) {
        System.err.println(e);
    }   
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIdActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Connection con;

    try {
        con = Conexion.getConexion();

        PreparedStatement ps = con.prepareStatement("DELETE FROM product WHERE productId=?");
        ps.setInt(1, Integer.parseInt(txtProductId.getText()));
        int res = ps.executeUpdate();

        if (res > 0) {
            JOptionPane.showMessageDialog(null, "product Eliminada");
        } else {
            JOptionPane.showMessageDialog(null, "Error al eliminar product","Error",JOptionPane.ERROR_MESSAGE);
        }
        limpiarCajas();
        con.close();
        cargarTabla();

    } catch (HeadlessException | NumberFormatException | SQLException e) {
        System.err.println(e);
    }
    }//GEN-LAST:event_btnEliminarActionPerformed
    private void cargarTabla1() throws SQLException{
        DefaultTableModel modeloTabla = (DefaultTableModel) tblProducts.getModel();
        
        if (txtBuscarproductos.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, completa el campo.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return; 
  
        }
        if (!esNumeroPositivo(txtBuscarproductos.getText())) {
        JOptionPane.showMessageDialog(null, "Ingrese solo números", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        modeloTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;

        
        try {
        java.sql.Connection con =Conexion.getConexion();  
        ps  = con.prepareStatement("SELECT * FROM product WHERE productId = ?");
        ps.setString(1, txtBuscarproductos.getText());
        
        rs = ps.executeQuery();
        rsmd=rs.getMetaData();
        columnas=rsmd.getColumnCount();
        
        while(rs.next()){
            Object[] fila= new Object[columnas];
            for(int indice =0; indice<columnas;indice++){
                fila[indice]=rs.getObject(indice+1);
            }
            modeloTabla.addRow(fila);
        }         
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.toString());
        }
    } 
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Connection con;
        try {
            con =Conexion.getConexion();  
            
            PreparedStatement psVerificar = con.prepareStatement("SELECT * FROM product WHERE productId = ?");
            psVerificar.setString(1, txtBuscarproductos.getText());
            ResultSet rs = psVerificar.executeQuery();
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "No existe el productId", "Error de inserción", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            PreparedStatement psVerificar1 = con.prepareStatement("SELECT * FROM product WHERE productId = ?");
            psVerificar1.setString(1, txtBuscarproductos.getText());
            ResultSet rs1 = psVerificar1.executeQuery();
            if (!rs1.next()) {
                JOptionPane.showMessageDialog(null, "No se ha realizado ninguna registro", "Error de inserción", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            cargarTabla1();
        } catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtBuscarproductos;
    private javax.swing.JTextField txtCategoryID;
    private javax.swing.JTextField txtDiscontinued;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReorderLeverl;
    private javax.swing.JTextField txtSupplierd;
    private javax.swing.JTextField txtUniprice;
    private javax.swing.JTextField txtUnitsON;
    private javax.swing.JTextField txtUnitsStock;
    // End of variables declaration//GEN-END:variables
}
